# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_feedbackmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='_DiseaseModel',
            new_name='DiseaseModel',
        ),
    ]
