# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170407_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
    ]
